### ISSUE TITLE
/test/test_readv.py fails to run on Ubuntu and FreeBSD

### ISSUE THREAD

**Issue by coder03** [ironport/shrapnel#83]
chatty@ubuntu:~shrapnel/test$ python test_readv.py
E
======================================================================
ERROR: test_readv (__main__.Test)
Test readv.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_readv.py", line 113, in test_readv
    '01234567'))
  File "test_readv.py", line 77, in testit
    blocks = coro.with_timeout(5, s.readv, block_receives)
  File "coro/_coro.pyx", line 1111, in coro._coro.sched.with_timeout (coro/_coro.c:16399)
TypeError: Argument 'size_list' has incorrect type (expected list, got tuple)

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
7:	Tue Dec  6 22:26:19 2016 thread 7 (<bound method TestSession.run of <__main__.TestSession instance at 0x7f1f252603f8>>): error '(\'coro/oserrors.pyx coro.oserrors.map_exception (coro/oserrors.c:874)|44\', "<class \'coro.oserrors.EPIPE\'>", \'[Errno 32] Broken pipe\', \'[coro/_coro.pyx coro._coro._wrap1 (coro/_coro.c:12115)|772] [test_readv.py run|63] [coro/socket.pyx coro._coro.sock.send (coro/_coro.c:27626)|282] [coro/socket.pyx coro._coro.sock.send (coro/_coro.c:27500)|314] [coro/pyrex_helpers.pyx coro._coro.raise_oserror (coro/_coro.c:3879)|32] [coro/oserrors.pyx coro.oserrors.map_exception (coro/oserrors.c:874)|44]\')'
chatty@ubuntu:~shrapnel/test$

**Comment by samrushing** [comment]
I tried changing the test to pass lists instead of tuples, that was not enough.  Now it's complaining that `'tuple' object does not support item assignment` on socket.pyx::559.

Looks like this kinda thing no longer works:

```python
x = PyTuple_New(1)
x[0] = 1
```

The code either needs to use PyTuple_SetItem (or something with a name similar to that), or needs to be rewritten in a simpler style that plays better with today's smarter Cython.
